{
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0",
    "cveMetadata": {
        "state": "PUBLISHED",
        "cveId": "CVE-2018-7536",
        "assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
        "assignerShortName": "mitre",
        "dateUpdated": "2023-12-07T22:05:43.713862",
        "dateReserved": "2018-02-26T00:00:00",
        "datePublished": "2018-03-09T00:00:00"
    },
    "containers": {
        "cna": {
            "providerMetadata": {
                "orgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
                "shortName": "mitre",
                "dateUpdated": "2023-12-07T22:05:43.713862"
            },
            "descriptions": [
                {
                    "lang": "en",
                    "value": "An issue was discovered in Django 2.0 before 2.0.3, 1.11 before 1.11.11, and 1.8 before 1.8.19. The django.utils.html.urlize() function was extremely slow to evaluate certain inputs due to catastrophic backtracking vulnerabilities in two regular expressions (only one regular expression for Django 1.8.x). The urlize() function is used to implement the urlize and urlizetrunc template filters, which were thus vulnerable."
                }
            ],
            "affected": [
                {
                    "vendor": "n/a",
                    "product": "n/a",
                    "versions": [
                        {
                            "version": "n/a",
                            "status": "affected"
                        }
                    ]
                }
            ],
            "references": [
                {
                    "name": "USN-3591-1",
                    "tags": [
                        "vendor-advisory"
                    ],
                    "url": "https://usn.ubuntu.com/3591-1/"
                },
                {
                    "name": "RHSA-2019:0051",
                    "tags": [
                        "vendor-advisory"
                    ],
                    "url": "https://access.redhat.com/errata/RHSA-2019:0051"
                },
                {
                    "name": "[debian-lts-announce] 20180308 [SECURITY] [DLA 1303-1] python-django security update",
                    "tags": [
                        "mailing-list"
                    ],
                    "url": "https://lists.debian.org/debian-lts-announce/2018/03/msg00006.html"
                },
                {
                    "name": "103361",
                    "tags": [
                        "vdb-entry"
                    ],
                    "url": "http://www.securityfocus.com/bid/103361"
                },
                {
                    "url": "https://www.djangoproject.com/weblog/2018/mar/06/security-releases/"
                },
                {
                    "name": "RHSA-2019:0082",
                    "tags": [
                        "vendor-advisory"
                    ],
                    "url": "https://access.redhat.com/errata/RHSA-2019:0082"
                },
                {
                    "name": "RHSA-2018:2927",
                    "tags": [
                        "vendor-advisory"
                    ],
                    "url": "https://access.redhat.com/errata/RHSA-2018:2927"
                },
                {
                    "name": "RHSA-2019:0265",
                    "tags": [
                        "vendor-advisory"
                    ],
                    "url": "https://access.redhat.com/errata/RHSA-2019:0265"
                },
                {
                    "name": "DSA-4161",
                    "tags": [
                        "vendor-advisory"
                    ],
                    "url": "https://www.debian.org/security/2018/dsa-4161"
                },
                {
                    "url": "https://github.com/django/django/commit/1ca63a66ef3163149ad822701273e8a1844192c2"
                },
                {
                    "url": "https://github.com/django/django/commit/abf89d729f210c692a50e0ad3f75fb6bec6fae16"
                },
                {
                    "url": "https://github.com/django/django/commit/e157315da3ae7005fa0683ffc9751dbeca7306c8"
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "type": "text",
                            "lang": "en",
                            "description": "n/a"
                        }
                    ]
                }
            ],
            "datePublic": "2018-03-06T00:00:00"
        }
    }
}