{
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0",
    "cveMetadata": {
        "cveId": "CVE-2023-4570",
        "assignerOrgId": "bca5b2e8-03a4-4781-b4ca-c6a078c0bfd4",
        "state": "PUBLISHED",
        "assignerShortName": "NI",
        "dateReserved": "2023-08-28T19:32:41.324Z",
        "datePublished": "2023-10-05T15:26:45.467Z",
        "dateUpdated": "2023-10-05T15:26:45.467Z"
    },
    "containers": {
        "cna": {
            "affected": [
                {
                    "defaultStatus": "unaffected",
                    "modules": [
                        "Python Services"
                    ],
                    "product": "MeasurementLink ",
                    "vendor": "NI",
                    "versions": [
                        {
                            "lessThanOrEqual": "1.1.0",
                            "status": "affected",
                            "version": "1.0.0",
                            "versionType": "1.1.1"
                        }
                    ]
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "supportingMedia": [
                        {
                            "base64": false,
                            "type": "text/html",
                            "value": "<span style=\"background-color: rgb(255, 255, 255);\">An improper access restriction in NI MeasurementLink Python services could allow an attacker on an adjacent network to reach services exposed on localhost.  These services were previously thought to be unreachable outside of the node.  This affects measurement plug-ins written in Python using version 1.1.0 of the </span><span style=\"background-color: rgb(255, 255, 255);\">ni-measurementlink-service</span><span style=\"background-color: rgb(255, 255, 255);\">&nbsp;Python package and all previous versions.</span><br>"
                        }
                    ],
                    "value": "An improper access restriction in NI MeasurementLink Python services could allow an attacker on an adjacent network to reach services exposed on localhost.  These services were previously thought to be unreachable outside of the node.  This affects measurement plug-ins written in Python using version 1.1.0 of the ni-measurementlink-serviceÂ Python package and all previous versions.\n"
                }
            ],
            "impacts": [
                {
                    "capecId": "CAPEC-1",
                    "descriptions": [
                        {
                            "lang": "en",
                            "value": "CAPEC-1 Accessing Functionality Not Properly Constrained by ACLs"
                        }
                    ]
                }
            ],
            "metrics": [
                {
                    "cvssV3_1": {
                        "attackComplexity": "LOW",
                        "attackVector": "ADJACENT_NETWORK",
                        "availabilityImpact": "HIGH",
                        "baseScore": 8.8,
                        "baseSeverity": "HIGH",
                        "confidentialityImpact": "HIGH",
                        "integrityImpact": "HIGH",
                        "privilegesRequired": "NONE",
                        "scope": "UNCHANGED",
                        "userInteraction": "NONE",
                        "vectorString": "CVSS:3.1/AV:A/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                        "version": "3.1"
                    },
                    "format": "CVSS",
                    "scenarios": [
                        {
                            "lang": "en",
                            "value": "GENERAL"
                        }
                    ]
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "cweId": "CWE-420",
                            "description": "CWE-420 Unprotected Alternate Channel",
                            "lang": "en",
                            "type": "CWE"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "orgId": "bca5b2e8-03a4-4781-b4ca-c6a078c0bfd4",
                "shortName": "NI",
                "dateUpdated": "2023-10-05T15:26:45.467Z"
            },
            "references": [
                {
                    "url": "https://www.ni.com/en/support/documentation/supplemental/23/improper-restriction-in-ni-measurementlink-python-services.html"
                }
            ],
            "source": {
                "discovery": "UNKNOWN"
            },
            "title": "Improper Restriction in NI MeasurementLink Python Services",
            "x_generator": {
                "engine": "Vulnogram 0.1.0-dev"
            }
        }
    }
}